spring:
  application:
    name: spring-practice
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_db
    username: postgres
    password: password  # ← インストール時に設定したパスワードに変更してください
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.springframework.jdbc.core: INFO # DEBUG にすると実行されているSQLが出力される